// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace EnverSoft.SupplierConnect.Domain.Entities
{
    public partial class Supplier
    {
        public int Code { get; set; }

        public string Name { get; set; }

        public string TelephoneNo { get; set; }
    }
}